books = [
    {
        'id': 1,
        'title': 'Think Python',
        'author': 'Allen B. Downey',
        'publisher': "O'Reilly Media",
        'publisher_date': '2015-01-01',
        'pages': 288,
        'language': 'English',
    },
    {
        'id': 2,
        'title': 'Clean Code',
        'author': 'Robert C. Martin',
        'publisher': 'Prentice Hall',
        'publisher_date': '2008-08-01',
        'pages': 464,
        'language': 'English',
    },
    {
        'id': 3,
        'title': 'The Pragmatic Programmer',
        'author': 'Andrew Hunt',
        'publisher': 'Addison-Wesley',
        'publisher_date': '1999-10-30',
        'pages': 352,
        'language': 'English',
    },
    {
        'id': 4,
        'title': 'Design Patterns',
        'author': 'Erich Gamma',
        'publisher': 'Addison-Wesley',
        'publisher_date': '1994-10-21',
        'pages': 395,
        'language': 'English',
    },
    {
        'id': 5,
        'title': 'Introduction to Algorithms',
        'author': 'Thomas H. Cormen',
        'publisher': 'MIT Press',
        'publisher_date': '2009-07-31',
        'pages': 1312,
        'language': 'English',
    },
    {
        'id': 6,
        'title': 'Deep Learning',
        'author': 'Ian Goodfellow',
        'publisher': 'MIT Press',
        'publisher_date': '2016-11-18',
        'pages': 800,
        'language': 'English',
    },
]
